### ISSUE TITLE
Incorrect bean property

### ISSUE THREAD

**Issue by rlatela** [super-csv/super-csv#142]
Hello,

I'm trying to read a CSV file with the header but seems that name of the set method has an character in lowercase:
org.supercsv.exception.SuperCsvReflectionException: unable to find method **set﻿idOrder**(java.lang.Integer) 

The name of the bean property is idOrder and the Header is idOrder so the set name of the method should be setIdOrder.

Any suggestion?

Thank you for your support,
Raffaele Latela

[201805081341477_ORDERS.csv.zip](https://github.com/super-csv/super-csv/files/1984424/201805081341477_ORDERS.csv.zip)

**Comment by dota17** [comment]
This problem is caused by reading the UTF-8 bom file, and the file header has BOM information。
![image](https://user-images.githubusercontent.com/50514813/71390878-f5166400-263c-11ea-931c-832d11189cf8.png)

**Comment by dota17** [comment]
Hi, @rlatela 
This problem is caused by reading the UTF-8 bom file, and the file header has BOM information. For UTF-8, the BOM is EF BB BF. For UTF-16, the BOM is FE FF. So when you read the csv file, It is a problem with the header caused by the BOM informatio.
You can solve this problem by converting the file to UTF-8 without BOM format.
I will continue to focus on this issue, Thank you!

**Comment by dota17** [comment]
#164 is the PR fix this problem
