### ISSUE TITLE
Cobertura does not support java 1.8

### ISSUE THREAD

**Issue by dota17** [super-csv/super-csv#160]
The jar cobertura-maven-plugin does not support java 1.8 [#ISSUE21](https://github.com/mojohaus/cobertura-maven-plugin/issues/21), which caused super-csv-java8 project can not to get test  case coverage report. So is it necessary to use other tool(e.g jacoco) instead of cobertura?

**Comment by dota17** [comment]
Hi, @kbilsted 
What do you think of this problem?

**Comment by kbilsted** [comment]
What do you suggest as a solution  @dota17 ?

**Comment by kbilsted** [comment]
The choice of tool is really up to whatever is the favorite of who wants to help maintain the library

**Comment by jjenkov** [comment]
Personally, I feel the runtime using SuperCSV should take precedence over any build or reporting tools used during SuperCSV development. Hence, since Java 8 is one of the most used Java versions out there, I believe SuperCSV should be developed with support for Java 8. If Cobertura, in this day and age, still doesn't support Java 8, I think Cobertura should be downprioritized.

**Comment by kbilsted** [comment]
@jjenkov  I agree. 

Who are familiar with other coverage tools and who have an interest in driving them forward here?

**Comment by dota17** [comment]
Hi, @kbilsted 
Maybe we can try using jacoco to replace cobertura?

**Comment by kbilsted** [comment]
@dota17  You are welcome to try to integrate with jacoco
