### ISSUE TITLE
CsvPreference.getQuoteChar returns an int instead of char

### ISSUE THREAD

**Issue by jkot** [super-csv/super-csv#32]
First, thanks for the great library! I've just noticed a small inconsistency:

https://github.com/super-csv/super-csv/blob/master/super-csv/src/main/java/org/supercsv/prefs/CsvPreference.java#L175

quoteChar is declared as in CsvPreference: `char quoteChar`
but it returns an int:
```
public int getQuoteChar() {
		return quoteChar;
	}
```

that prevents doing: `new CsvPreference.Builder(CsvPreference.STANDARD_PREFERENCE.getQuoteChar(), CsvPreference.STANDARD_PREFERENCE.getDelimiterChar(), "\n").build();`

because the Builder expects a `char` again.

**Comment by kbilsted** [comment]
Sure. Don't recall why it was made like this. Feel free to submit a pull request.:)

**Comment by jamesbassett** [comment]
So it looks like the inconsistency (`char quoteChar` / `int delimiterChar`) has been around since [pre 2.0.0](https://github.com/super-csv/super-csv/blob/v1.52/src/org/supercsv/prefs/CsvPreference.java). The `CsvPreference` constructor would take char and int, but the getters both returned int. I retained this behaviour when creating the builder for 2.0.0.

Why `int`s? If Kasper can't recall then we'll never know :)  If we replaced all the `int`s with `char` it shouldn't be too much of a breaking change (people would normally be passing `char` literals into the builder).

I'm sure the above is just an example, but in that case you could simply use `CsvPreference.EXCEL_PREFERENCE` as it's the same as `STANDARD_PREFERENCE` but uses a `\n` as the line terminator.

**Comment by kbilsted** [comment]
Well. Let me see. It may originate from a time where it was, or it was believed to be, faster to compare against an int. Since the VM internally are converting lesser types to int upon processing. I think I recall it was faster, albeit less general, than using a string.

**Comment by kbilsted** [comment]
We have a benchmark suite, if we do not see a change of performance, I don't see why we could not change the type to `char`. Since we both agree to this, @jkot  feel free to PR us.
