### ISSUE TITLE
[question] Api to check whether cell-processor range contains a certain cell-processor.

### ISSUE THREAD

**Issue by ptahchiev** [super-csv/super-csv#52]
Hello,

I have a cell-processor which internally has another cell-processor inside `next` attribute, which has another cell-processor, and so on. I would like to ask if there's an API to check whether somewhere in this chain the `ParseBool` cell processor is met. Of course I can write my own method, but I just want to know if there's one already written.

Thanks.

**Comment by jamesbassett** [comment]
Hi Petar, no there's nothing in the API like that. Generally cell processors should have no idea about the other processors in the chain - so you'll have to write your own. It will be a bit ugly, as you'll have to do `instanceof` checks and cast to `CellProcessorAdaptor` to get the next processor in the chain (you'll know you've reached the end of the chain because the last processor, `NullObjectPattern`, won't extend this class).

**Comment by kbilsted** [comment]
Yes @jamesbassett is does seem a bit exotic to have such need, but my guess is that @ptahchiev  is dynamically building the chain of processors. And probably it would confuse users if we add too much of that stuff in here - or maybe they will never be able to find it. So I'd lean against not getting this inside the framework itself, but @ptahchiev  i'd be nice to share your snippet as a gist..
