### ISSUE TITLE
Super CSV JSR 310 support

### ISSUE THREAD

**Issue by ludovicofischer** [super-csv/super-csv#53]
Hi,

I have created default parsers and formatters for the JSR310 date types https://github.com/ludovicofischer/super-csv-jsr310. Would you be interested in having it inside the main supercsv repository like the Joda formatters? The code is a port of the joda extras. It works but it needs some more testing.

**Comment by jamesbassett** [comment]
Hi Ludovico, yeah I think that'd be really useful. It's good that the Java 8 time API is so similar to Joda :)

Maybe we should have a `super-csv-java8` module, so we're not limited to just Java 8 time cell processors? @kbilsted what are your thoughts?

Hopefully this can just be another module of the `super-csv` project (it just overrides the compiler settings, javadoc settings, etc), but if that proves to hard, then maybe it should just be another repo. Then if someone wants to do a rewrite for Java 8 it has a home :)

**Comment by ludovicofischer** [comment]
`super-csv-java8` is a good idea, although I don’t know what other types JDK8 introduces besides the date and time that are likely to be found in a CSV. I would be happy to merge back into the supercsv repository I hope it’s possible to build a maven submodule with different source level and target.

**Comment by kbilsted** [comment]
@ludovicofischer  Thanks for the idea and code. Its a great idea

@jamesbassett  I think a new module will be great. We preserve backward compability, yet stay on par with the latest development. For example, since java8 has lambda expressions, we can now make a cellprocessor that takes a lambda, that way a lot of chaining and custom cell procor-writing can be simplified away. I'm not too strong on the multi-module aspect. Would you create the module ? Then we can look at including @ludovicofischer code onto it and do other java8 great stuff

**Comment by jamesbassett** [comment]
Ok @kbilsted @ludovicofischer I've created the Java 8 module (see PR #57). Let me know what you think :)

**Comment by kbilsted** [comment]
+1

**Comment by ludovicofischer** [comment]
Did you just add support for LocalDate? I could transplant the code from my own project on top of yours to supply convertes for the other time classes.

**Comment by jamesbassett** [comment]
Yeah I needed at least one class and test class to test that everything works properly (compilation, distribution zip file, javadoc, site, etc), but I wanted to leave you with the opportunity to add everything else.

So feel free to submit a PR :)

**Comment by ludovicofischer** [comment]
I’m on it. I have a question, though. How is it possible that the current tests for the Joda package pass in all locales if they check the results against hard-coded strings? Making sure that my tests would work in any locale was on my to-do list.

**Comment by jamesbassett** [comment]
Haha magic! I suspect that's because I used locale-independant date format strings, e.g.

    DATE_TIME_FORMAT = "yyyy-MM-dd'T'hh:mm:ss.SSSZZ";

If I'd put an `E` in there it would become locale dependent.

You've probably seen that there's a few maven profiles for different locales, and the travis build compiles each one. So we could easily add extra tests to check for locale-dependent values if we wanted to. I also use `Locale.ENGLISH` whenever the processor could be configured with a locale - once again just to make the tests simpler (so I could cheat and iterate over all the various processors and expect the same output).

**Comment by ludovicofischer** [comment]
Thanks for the information about date format strings! One more question: you are using tabs instead of spaces in this project, right?

**Comment by jamesbassett** [comment]
I believe so. Which IDE do you use? I prefer Intellij, but I tend to use Eclipse for Super CSV as the formatter/code style files are checked into the project. So once you set up the eclipse project to use them, you won't have to worry about it.

**Comment by ludovicofischer** [comment]
I use Intellij. I have imported the Eclipse forrmatter settings http://blog.jetbrains.com/idea/2014/01/intellij-idea-13-importing-code-formatter-settings-from-eclipse/.

**Comment by jamesbassett** [comment]
Well that's awesome - goodbye Eclipse!

**Comment by ZioberMichal** [comment]
I also use IntelliJ. You can export your's IntelliJ settings, if you are sure they are the same as Eclipse's, and commit to repo. It is much easier to import IntelliJ's settings that Eclipse's.
