### ISSUE TITLE
Error with quotation marks("") when write CSV

### ISSUE THREAD

**Issue by astrung** [super-csv/super-csv#69]
when i use SUPERCSV to write a file with this format:
"column_1","column_2","column_3",...
But with this cell format:
        final CellProcessor[] processors = new CellProcessor[] { 
                new NotNull(), // paragraph_id (must be unique)
                new NotNull(), // company_name
                new NotNull(), // text
                new NotNull(), // words
                new NotNull(), // POS_tags
        };
        
        return processors;
Only from column 3 to 5 has quotation marks(" ").Column 1 and 2 dont  have any quotation marks.
So how to insert quotation marks in column 1 and 2??

**Comment by kbilsted** [comment]
If I'm understanding you correctly the following is from the documentation: http://super-csv.github.io/super-csv/preferences.html


Custom quote mode
By default Super CSV only adds surrounding quotes when writing CSV when it contains a delimiter, quote or newline (or if you've enabled surroundingSpacesNeedQuotes and the value has surrounding spaces).

Super CSV provides two alternative quoting modes:

AlwaysQuoteMode - quotes are always applied
ColumnQuoteMode - quotes are always applied for particular columns
You can also write your own QuoteMode, but please note that this is a means to enable quotes when they're not normally required (you won't be able to disable quotes because then your CSV will not be readable if it contains embedded special characters). Just pass your desired mode to the useQuoteMode() method when building your preferences:

private static final CsvPreference ALWAYS_QUOTE = 
    new CsvPreference.Builder(CsvPreference.STANDARD_PREFERENCE).useQuoteMode(new AlwaysQuoteMode().build();

**Comment by kbilsted** [comment]
Closing.. no reaction from asker

**Comment by macleodmac** [comment]
There's a close bracket missing, the correct code is:

`private static final CsvPreference ALWAYS_QUOTE = new CsvPreference.Builder(CsvPreference.STANDARD_PREFERENCE).useQuoteMode(new AlwaysQuoteMode()).build();`

Cheers.
